name: Assignment Pull Request Creator
description: Scans for assignment folders and creates a pull request for each assignment. Supports dry-run mode to simulate operations without making changes.
author: majikmate

inputs:
  github-token:
    description: GitHub token for API access
    required: true
  default-branch:
    description: Default branch to create pull requests against
    required: false
    default: main
  assignment-regex:
    description: List of regular expressions - one per line - to match assignment paths and extract branch names using capturing groups. Use (?P<name>...) for named groups or (...) for unnamed groups. Named groups take priority when both are present.
    required: false
    default: |
      ^assignments/(assignment-\d+)$
  protected-folder-regex:
    description: List of regular expressions - one per line - to match folder paths that should be protected.
    required: false
    default: |
      ^.devcontainer$
      ^.github$
      ^tutorials$
  dry-run:
    description: Simulate operations without actually creating branches or pull requests
    required: false
    default: "false"

outputs:
  created-branches:
    description: List of branches created
    value: ${{ steps.create-assignments.outputs.created-branches }}
  created-pull-requests:
    description: List of pull requests created
    value: ${{ steps.create-assignments.outputs.created-pull-requests }}

runs:
  using: composite
  steps:
    - name: Install assignment-pr-creator
      shell: bash
      env:
        ACTION_REF: ${{ github.action_ref }} # tag or SHA; empty when caller used a branch (e.g. @main)
        ACTION_SHA: ${{ github.action_sha }} # always the resolved commit SHA
      run: |
        echo "Installing assignment-pr-creator from GitHub..."

        echo "ACTION_REF: '$ACTION_REF'"
        echo "ACTION_SHA: '$ACTION_SHA'"

        if [ -n "$ACTION_REF" ]; then
          REF_FOR_GO="$ACTION_REF"
          echo "Using action reference: $REF_FOR_GO"
        elif [ -n "$ACTION_SHA" ]; then
          REF_FOR_GO="$ACTION_SHA"
          echo "Using resolved commit: $REF_FOR_GO"
        else
          # Last-resort fallback
          REF_FOR_GO="main"
          echo "⚠️  No action ref/SHA available; falling back to '$REF_FOR_GO'."
        fi

        if [[ ! "$REF_FOR_GO" =~ ^v[0-9]+(\.[0-9]+)*$ ]]; then
          echo "⚠️  Installing from non-release ref ($REF_FOR_GO). Consider pinning to a release tag for production."
        fi

        go install github.com/majikmate/assignment-pull-request/cmd/assignment-pr-creator@"$REF_FOR_GO"
        echo "✅ assignment-pr-creator installed"

    - name: Configure Git
      shell: bash
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"

    - name: Run assignment-pr-creator
      id: create-assignments
      shell: bash
      working-directory: ${{ github.workspace }}
      env:
        GITHUB_TOKEN: ${{ inputs.github-token }}
        GITHUB_REPOSITORY: ${{ github.repository }}
        DEFAULT_BRANCH: ${{ inputs.default-branch }}
        ASSIGNMENT_REGEX: ${{ inputs.assignment-regex }}
        PROTECTED_FOLDER_REGEX: ${{ inputs.protected-folder-regex }}
        DRY_RUN: ${{ inputs.dry-run }}
      run: |
        assignment-pr-creator

branding:
  icon: git-pull-request
  color: blue
